package de.micromata.genome.tpsb.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * In case using in a TestSuite dynamicall generated by TestSuite, This annotation marks the pattern, for looking scenario files.
 * 
 * Sample see vls AutoShipmentValidationTest.
 * 
 * @author Roger Rene Kommer (r.kommer.extern@micromata.de)
 * 
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface TpsbScenarioSuiteFiles {
  /**
   * Pattern to build the file name.
   * 
   * ${0} is used as placeholder.
   * 
   * Note currently only ${0} direct after directory is supported:
   * 
   * <code>a/b/${0}_props.txt</code> is ok. <code>a/b/blub${0}_props.txt</code> is not ok.
   * 
   * @return
   */
  String filePattern() default "${0}";
}
