//
// Copyright (C) 2010-2016 Micromata GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package de.micromata.genome.tpsb.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * In case using in a TestSuite dynamicall generated by TestSuite, This annotation marks the pattern, for looking scenario files.
 * 
 * 
 * @author Roger Rene Kommer (r.kommer.extern@micromata.de)
 * 
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface TpsbScenarioSuiteFiles {
  /**
   * Pattern to build the file name.
   * 
   * ${0} is used as placeholder.
   * 
   * Note currently only ${0} direct after directory is supported:
   * 
   * <code>a/b/${0}_props.txt</code> is ok. <code>a/b/blub${0}_props.txt</code> is not ok.
   * 
   * @return the file pattern
   */
  String filePattern() default "${0}";
}
